version: "3.8"

services:
    backend:
        image: vascoalramos/roomie-backend
        ports:
            - 8083:8083
        depends_on:
            - postgres

    postgres:
        image: postgres
        restart: unless-stopped
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=roomie
            - POSTGRES_USER=roomie
            - POSTGRES_PASSWORD=passw0rd
        volumes:
            - database-data:/var/lib/postgresql/data/

volumes:
    database-data:
