version: "3.8"

services:
    web-server:
        image: vascoalramos/roomie-web
        ports:
            - 80:80
        depends_on:
            - postgres
            - app-server
        deploy:
            replicas: 3
            restart_policy:
                condition: any

    app-server:
        image: vascoalramos/roomie-app
        ports:
            - 8083:8083
        depends_on:
            - postgres
        volumes:
            - /nfs/roomie/images:/usr/src/app/images:z
            - /nfs/roomie/uploads:/usr/src/app/uploads:z
        deploy:
            replicas: 3
            restart_policy:
                condition: any

    postgres:
        image: postgres
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=roomie
            - POSTGRES_USER=roomie
            - POSTGRES_PASSWORD=passw0rd
        command: ["-c", "max_connections=1000"]
        volumes:
            - /nfs/roomie/pg:/var/lib/postgresql/data/:z
        deploy:
            replicas: 1
            restart_policy:
                condition: any

volumes:
    database-data: