---

- name: Update apt repositories
  become: yes
  apt:
    update_cache: yes

- name: Upgrade system packages
  become: yes
  apt:
    name: "*"
    state: latest

- name: Disable SSH password authentication
  become: yes
  copy:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    backup: yes
    force: no
  notify: "Restart ssh"

- name: Install required system packages
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - nfs-common
      - python3-pip
      - nano
    state: latest

- name: Install required Python packages
  become: yes
  pip:
    name:
      - jsondiff
      - pyyaml
      - docker

- name: Mount NFS Disk
  become: yes
  ansible.posix.mount:
    src: '{{ hostvars["localhost"].nfs_disk.networks[0].ipAddresses[0] }}:/share_nfs'
    path: /nfs
    fstype: nfs
    opts: rw
    state: mounted

- name: Create NFS directories
  become: yes
  run_once: true
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0777'
  loop:
    - /nfs/roomie/pg
    - /nfs/roomie/images
    - /nfs/roomie/uploads
