plugin: gcp_compute
auth_kind: serviceaccount
service_account_file: ./roomie.json
projects:
  - roomie-312016
keyed_groups:
  - key: labels['type']
    separator: ""
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  internal_ip: networkInterfaces[0].networkIP
