---

- name: Scale containers
  hosts: managers
  run_once: true
  become: yes
  tasks:
      - name: Scale web service containers
        shell: "docker service scale roomie_frontend={{ lookup('vars', 'frontend') | int }}"
        when: frontend is defined
      
      - name: Scale celery service containers
        shell: "docker service scale roomie_backend={{ lookup('vars', 'backend') | int }}"
        when: backend is defined
